const {Sequelize, sequelize}  = require('./connect');


const CurrencyShop = 
require('./models/CurrencyShop.js')(sequelize, Sequelize.DataTypes);
require('./models/Users.js')(sequelize, Sequelize.DataTypes);
require('./models/UserItems.js')(sequelize, Sequelize.DataTypes);

const force = process.argv.includes('--force') || process.argv.includes('-f');

const abilityEmoji = ':ability:980090964876070963'; //green
const proficiencyyEmoji = ':proficiency:980090964972539974'; //yellow
const boostEmoji = ':boost:980090964850905138'; //blue
const difficultyEmoji = ':difficulty:980090964859289640';
const challengeEmoji = ':challenge:980090964867678248';
const setbackEmoji = ':setback:980090965245186130';
const successEmoji = ':success:980090964964151306';
const advantageEmoji = ':advantage:980090964859314236';
const triumphEmoji = ':triumph:980090965199048734';
const failureEmoji = ':failure:980090964905451550';
const threatEmoji = 'threat:980090964905443328';
const despairEmoji = ':despair:980090965043867678';


// <${abilityEmoji}>
// <${proficiencyEmoji}>
// <${boostEmoji}>
// <${difficultyEmoji}>
// <${challengeEmoji}>
// <${setbackEmoji}>
// <${successEmoji}>
// <${advantageEmoji}>
// <${triumphEmohi}>
// <${failureEmoji}>
// <${threatEmoji}>
// <${despairEmoji}>
// 



sequelize.sync({ force }).then(async () => {
    const shop = [

        CurrencyShop.upsert({ name: 'Comlink (handheld)', search_name: 'comlink (handheld)', cost: 25, item_encumberance: 0, item_rarity: 0, item_description: `This piece of gear is used to communicate between other comlinks. The handheld versions are only viable for extreme distances on planets, reaching up to low orbit. However, long range versions can usually reach the entire planet in range.`, item_restricted: `No`}),
        CurrencyShop.upsert({ name: 'Field Ration Pack', search_name: 'field ration pack', cost: 5, item_encumberance: 0, item_rarity: 0, item_description: `Single meal`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Mk. III Modular Backpack', search_name: 'mk. iii modular backpack', cost: 75, item_encumberance: 0, item_rarity: 1, item_description: `Increases encumbrance threshold by 2. Extra pockets increase the encumbrance threshold by 1 (6 can be attached)`, item_restricted: `No`}),
        CurrencyShop.upsert({ name: '3-MAL Secure Comlink', search_name: '3-mal secure comlink', cost: 250, item_encumberance: 0, item_rarity: 4, item_description: `This is an extremely small comlink with military-grade encryption, favoured by the rebel alliance and civil emergency services. Add 1 <${setbackEmoji}> die to intercept and decrypt the signal. Monitoring a clear frequency on a civilized world adds 2 <${boostEmoji}><${boostEmoji}> dice to Knowledge check related to current events.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Atgar Artillery Remote', search_name: 'atgar artillery remote', cost: 400, item_encumberance: 1, item_rarity: 7, item_description: `A device used to link a single Gunnery weapon to an Atgar Artillery Remote with a Computers (<${difficultyEmoji}><${difficultyEmoji}><${difficultyEmoji}>) check. If the weapon is an Atgar Space Defense Corporation model, this check is (<${difficultyEmoji}><${difficultyEmoji}>) instead. If the check succeeds, the weapon gains the Inaccurate 2 quality and the holder of the remote can fire the linked weapon via the remote from up to medium range.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Bespin Motors Remote DVI Activator', search_name: 'bespin motors remote dvi activator', cost: 300, item_encumberance: 0, item_rarity: 4, item_description: `Sometimes, one needs to make a speedy getaway, but starships take their time to start up and get through their pre-flight checks. This remote allows one to jump-start their ship before they've arrived so that they can lift-off immediately upon arrival. May activate a ship from 5 km away, running pre-flight checks to have it ready to go. May potentially pilot a slave circuit with a Daunting (<${difficultyEmoji}><${difficultyEmoji}><${difficultyEmoji}><${difficultyEmoji}>) Piloting check.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Carbanti United Electronics Whistler', search_name: 'carbanti united electronics whistler', cost: 1250, item_encumberance: 3, item_rarity: 6, item_description: `This unit is used to encrypt messages with a cypher that is all but uncrackable, used by diplomats and military organisations to send the most secret messages to operatives. Without decryption key, decoding a message sent through this equipment requires a Formidable (<${difficultyEmoji}><${difficultyEmoji}><${difficultyEmoji}><${difficultyEmoji}><${difficultyEmoji}>) check and sophisticated equipment.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Chedak Communications X-500 Portable HoloNet Relay', search_name: 'chedak communications x-500 portable holonet relay', cost: 75000, item_encumberance: 15, item_rarity: 7, item_description: `Although reserved primarily for military communications, the HoloNet is still used by civilians for communications and media transmission instantly across the galaxy. A relay such as this one may be the only option colonists have to communicate across the galaxy. Allows communication using the HoloNet.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Cirenian Communications Pioneer Long-Range Transceiver', search_name: 'cirenian communications pioneer long-range transceiver', cost: 1000, item_encumberance: 5, item_rarity: 5, item_description: `Also known as subspace transceivers, this equipment is a portable version of what is found on virtually all starships. Often this is used by smugglers and pirates who do not want to use the public HoloNet. Range up to 25 lightyears (further if bounced through a network within range).`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Combat Scanner', search_name: 'combat scanner', cost: 2000, item_encumberance: 1, item_rarity: 6, item_description: `Typically built into a helmet, these scanners provide users with critical battlefield data. The scanner includes an encrypted long-range comlink and a set of sensors. Remove (<${setbackEmoji}><${setbackEmoji}>) added to checks due to darkness/ see normally in dark conditions. Enemies add (<${setbackEmoji}><${setbackEmoji}>) )to checks made to intercept or decrypt data broadcasts.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Comlink (long-range)', search_name: 'comlink (long-range)', cost: 200, item_encumberance: 2, item_rarity: 1, item_description: `This piece of gear is used to communicate between other comlinks. The handheld versions are only viable for extreme distances on planets, reaching up to low orbit. However, long range versions can usually reach the entire planet in range.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'DH77 Headcomm', search_name: 'dh77 headcomm', cost: 400, item_encumberance: 0, item_rarity: 3, item_description: `This comlink is the standard one used by Imperial stormtroopers. However, due to the size specifications, it lacks power to reach long ranges. Transmits up to Medium range (Planetary Scale). Add (<${setbackEmoji}><${setbackEmoji}><${setbackEmoji}>) to decrypting intercepted`, item_restricted: `Yes` }),
        CurrencyShop.upsert({ name: 'Earbud Comlink', search_name: 'earbud comlink', cost: 75, item_encumberance: 0, item_rarity: 5, item_description: `This small comlink is convenient for users that need their hands free or a more inconspicuous form of communication. Usable at long range. Noticing the earbud comlink requires a (<${difficultyEmoji}><${difficultyEmoji}><${difficultyEmoji}>) Perception check.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'False Voice Transmitter', search_name: 'false voice transmitter', cost: 1400, item_encumberance: 4, item_rarity: 6, item_description: `The FVT is a combination of multiple pieces of technology which allows an operative to take a voice sample and then transmit messages via comlink with the replicated voice. Upgrade ability of Charm/Coercion/Deception/Leadership/Negotiation checks while impersonating another individual once.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Hardened Comlink', search_name: 'hardened comlink', cost: 450, item_encumberance: 4, item_rarity: 5, item_description: `This military grade comlink is built to withstand battlefield use and features satellite uplink capability. These are also encrypted and generally housed in a helmet. Add (<${failureEmoji}><${failureEmoji}>) result to any checks made to decode transmissions. Add (<${successEmoji}><${successEmoji}>) result to any checks user makes to break through a comms jammer.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Herzfall Communications Collar-Amp', search_name: 'herzfall communications collar-amp', cost: 50, item_encumberance: 0, item_rarity: 1, item_description: `This simple device is capable of filtering out surround sound by detecting the wearer's voice and amplify the output sound. It is often used by politicians and law enforcement - but occasionally performers have similar models. Boost wearer's voice to be heard at long or extreme range.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Herzfall Communications Collar-Amp (Extras)', search_name: 'herzfall communications collar-amp (extras)', cost: 150, item_encumberance: 0, item_rarity: 1, item_description: `This simple device is capable of filtering out surround sound by detecting the wearer's voice and amplify the output sound. It is often used by politicians and law enforcement - but occasionally performers have similar models. Boost wearer's voice to be heard at long or extreme range. For 100 credits extra, can purchase model which is able to hook into a sound or entertainment system for increased quality.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Holo-Megacaster', search_name: 'holo-megacaster', cost: 600, item_encumberance: 1, item_rarity: 3, item_description: `Used by many public speakers, the megacaster allows for the projection of one's voice - enhanced and louder. Further, this allows one to also project a holographic image of oneself up to 10 metres in size, so that their person may be seen as they talk. Add (<${boostEmoji}>) to Presence-based checks to address a crowd, may be seen and heard up to extreme range.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Holo-Messenger', search_name: 'holo-messenger', cost: 250, item_encumberance: 0, item_rarity: 4, item_description: `This is a small hightech piece of equipment which takes the comlink to a new level. It allows a holographic display to be sent along with the message, and may send a pre-recorded or continuous transmission. They have the range of a long range comlink.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Integrated Public Address System', search_name: 'integrated public address system', cost: 200, item_encumberance: 4, item_rarity: 4, item_description: `This is a portable package containing a set of speakers, power pack and microphone. The power unit allows this system to last an hour.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Polis Massan Voicebox', search_name: 'polis massan voicebox', cost: 50, item_encumberance: 1, item_rarity: 6, item_description: `Often attached to their body suits, the voicebox uses a neural connection to translate a Polis Massan's telepathic thoughts into speech - though it does sound like a droid.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'PTP Link', search_name: 'ptp link', cost: 100, item_encumberance: 2, item_rarity: 7, item_description: `This special type of comms device has a range of 25 kilometres, and due to the ancient aspect of the technology, most communicator devices are incapable of interacting or intercepting the link. It can be made undetectable by a PTP Encryption Package.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'PTP Encryption Device', search_name: 'ptp encryption device', cost: 1000, item_encumberance: 0, item_rarity: 7, item_description: `Makes a PTP Link broadcast undetectable.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Verpine Comlink', search_name: 'verpine comlink', cost: 250, item_encumberance: 1, item_rarity: 6, item_description: `This is a comlink that has been modified and tuned into the specific wavelength used by Verpine non-verbal communications. Can pick up on all Verpine hive communication within 100 km.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Adrenal Implant', search_name: 'adrenal implant', cost: 2250, item_encumberance: 0, item_rarity: 5, item_description: `This implant allows for the artificial stimulation of the adrenal gland for quicker recovery from physical strain. This allows for more endurance from the subject. Provides 1 rank in the Rapid Recovery talent.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: `Appraiser's Eye`, search_name: `appraiser's eye`, cost: 700, item_encumberance: 0, item_rarity: 7, item_description: `This cybernetic eye or retinal implant involves a number of sensors to allow estimation of value of whatever is being sold or bought. Add automatic <${advantageEmoji}> on Negotiation and Streetwise checks to buy or sell items.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Avionics Interface', search_name: 'avionics interface', cost: 8000, item_encumberance: 0, item_rarity: 6, item_description: `This cybernetic implant improves a pilot's ability at flying through atmosphere or in space, allowing the user to link their brain to the flight-systems of most advanced vehicles and starships. Piloting (Planetary or Space) skill +1, if already benefiting from a rank in that skill, when flying in a starship or airspeeder.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Biofeedback Regulator', search_name: 'biofeedback regulator', cost: 3000, item_encumberance: 0, item_rarity: 8, item_description: `This is a complex full-body implant which does little on its own, but enhances a biological vessel for carrying cybernetic implants. It is capable of redirecting bio-electricity for powering limbs and regulates the body's defenses to avoid implant rejection. Increase cybernetic cap by 2, this implant doesn't count towards the implant cap. Can only install 1, and droids may not install this.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Cortex Bomb', search_name: 'cortex bomb', cost: 1200, item_encumberance: 0, item_rarity: 6, item_description: `This is essentially a high-tech suicide pill, used by governments who care especially little for the safety of their agents - relative to the safety of intelligence. The bomb kills the wearer when the individual speaks/hears/sees a pre-determined code-word or signal. Deals little damage to target and no damage to surrounding area.`, item_restricted: `Yes` }),
        CurrencyShop.upsert({ name: 'Cyber Disguise', search_name: 'cyber disguise', cost: 18000, item_encumberance: 0, item_rarity: 8, item_description: `This cybernetic implant involves multiple systems embedded beneath the skin, which allows for drastic changes to appearance. It is an extremely invasive full-body implant, used by the most deep-cover agents. Counts as a standard disguise kit. Count as having 2 ranks in the "Indistinguishable" talent. Changing general features requires 1-3 rounds. Taking the appearance of a specific individual requires through study and a Hard (<${difficultyEmoji}><${difficultyEmoji}><${difficultyEmoji}>) Deception check. Cannot change general shape or size, or add/subtract limbs.`, item_restricted: `Yes` }),
        CurrencyShop.upsert({ name: 'Cybernetic Arms (Mod V)', search_name: 'cybernetic arms (mod v)', cost: 10000, item_encumberance: 0, item_rarity: 6, item_description: `These arms are built to replace lost limbs, but some may choose to replace a limb with these superior technical ones. They are bought separately. Mod V cyber-arms provide +1 to the Brawn characteristic. Mod VI cyber-arms provide +1 to the Agility characteristic. These may not be mixed together, and bonuses do not stack if two arms are replaced.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Cybernetic Arms (Mod VI)', search_name: 'cybernetic arms (mod vi)', cost: 10000, item_encumberance: 0, item_rarity: 6, item_description: `These arms are built to replace lost limbs, but some may choose to replace a limb with these superior technical ones. They are bought separately. Mod V cyber-arms provide +1 to the Brawn characteristic. Mod VI cyber-arms provide +1 to the Agility characteristic. These may not be mixed together, and bonuses do not stack if two arms are replaced.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Cybernetic Brain Implant', search_name: 'cybernetic brain implant', cost: 10000, item_encumberance: 0, item_rarity: 6, item_description: `This implant is well known as a primary enhancement used by most cyborgs. It essentially adds an extra computer to the natural brain's ability. This implant grants a +1 to the Intellect characteristic. It also has a built-in comlink and computer access link.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Cybernetic Cavity', search_name: 'cybernetic cavity', cost: 775, item_encumberance: 0, item_rarity: 4, item_description: `Sometimes a smuggler needs to traffic contraband through extremely vigorous security checkpoints. This implant allows one to hide items inside their body in a safe way. Provides 1 rank of Hidden Storage talent. Can use the talent to hide an item in their own body.`, item_restricted: `Yes` }),
        CurrencyShop.upsert({ name: 'Cybernetic Eyes', search_name: 'cybernetic eyes', cost: 7500, item_encumberance: 0, item_rarity: 6, item_description: `Although primarily used to restore sight to the blind, some may install these as an enhancement to their sight. These implants provide +1 skill rank to the Vigilance & Perception skills`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Cybernetic Legs (Mod II)', search_name: 'cybernetic legs (mod ii)', cost: 10000, item_encumberance: 0, item_rarity: 6, item_description: `These legs are built to replace lost limbs, but some may choose to replace a limb with these superior technical ones. Mod II cyber-legs provide +1 to the Brawn characteristic. Mod III cyber-legs provide +1 to the Agility characteristic. These may not be mixed together, and bonuses only apply if both legs are replaced.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Cybernetic Legs (Mod III)', search_name: 'cybernetic legs (mod iii)', cost: 10000, item_encumberance: 0, item_rarity: 6, item_description: `These legs are built to replace lost limbs, but some may choose to replace a limb with these superior technical ones. Mod II cyber-legs provide +1 to the Brawn characteristic. Mod III cyber-legs provide +1 to the Agility characteristic. These may not be mixed together, and bonuses only apply if both legs are replaced.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Cybernetic Reflexes', search_name: 'cybernetic reflexes', cost: 2750, item_encumberance: 0, item_rarity: 5, item_description: `These implants stimulate and regulate the sympathetic nervous system to artificially speed up reaction time to outside stimuli and threats, reducing the latency of neural communication. Provides 1 rank of the Rapid Reaction talent.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Cybernetic Respirator', search_name: 'cybernetic respirator', cost: 2000, item_encumberance: 0, item_rarity: 4, item_description: `This implant allows one to avoid suffering from the effects of airborne toxins and to breathe beneath the water - or even a completely airless environment for a short time. Provides benefits of a breath mask and respirator permanently. Provides 1 rank of the Blooded talent.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Cybernetic Weapon Implant', search_name: 'cybernetic weapon implant', cost: 4000, item_encumberance: 0, item_rarity: 7, item_description: `This cybernetic arm appears as a normal one, however features a retractable light blaster pistol. This allows the user to deploy a Light Blaster Pistol and fire it as if held normally.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Cyberscanner Limb', search_name: 'cyberscanner limb', cost: 4000, item_encumberance: 0, item_rarity: 7, item_description: `This cybernetic arm contains a scanner which projects a holographic screen which gives information about objects and the environment up to medium range. Includes a general purpose scanner.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Digital Lockpick', search_name: 'digital lockpick', cost: 2750, item_encumberance: 0, item_rarity: 5, item_description: `This prosthetic replaces a finger with a set of deployable small tools that allow one to get through both physical and digital locks. Provides 1 rank of Bypass Security talent.`, item_restricted: `Yes` }),
        CurrencyShop.upsert({ name: 'Escape Circuit', search_name: 'escape circuit', cost: 1000, item_encumberance: 0, item_rarity: 6, item_description: `Free droids are disgusted by the idea of being brought back into servitude. Restraining bolts would accomplish that if they ever were captured by a nefarious group. The escape circuit augments the droid brain in order to resist the bolt's effects. This may only be installed in droids. Allows resistance to a restraining bolt with an Easy (<${difficultyEmoji}>) Discipline check instead of (<${difficultyEmoji}><${difficultyEmoji}>) difficulty. Spend (<${advantageEmoji}><${advantageEmoji}>) to overload the bolt.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Gank Comm Implant', search_name: 'gank comm implant', cost: 250, item_encumberance: 0, item_rarity: 7, item_description: `The implants allow for communication via thought, being placed in a user's neocortex. Most adult Gank have these, allowing unmatched coordination. Can communicate silently with others using the implant within a range of several kilometres. Jammers can disrupt the signals.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Immune Implant', search_name: 'immune implant', cost: 5000, item_encumberance: 0, item_rarity: 6, item_description: `This cybernetic implant is able to react to the presence of pathogens or toxins in the body and automatically release a cocktail of medical drugs to combat it. Grants the skill Resilience +1.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: 'Implant Armour', search_name: 'implant armour', cost: 7500, item_encumberance: 0, item_rarity: 7, item_description: `This cybernetic is a set of ceramic-plasteel plates which are implanted beneath the skin to protect the individual further than simple armour. Provides Soak +1.`, item_restricted: `No`,item_soak_bonus: 1 }),
        CurrencyShop.upsert({ name: 'Implanted Cyberjack', search_name: 'implanted cyberjack', cost: 3750, item_encumberance: 0, item_rarity: 6, item_description: `Often a prosthetic finger which allows a user to interface directly with computer systems, this implant is popular with slicers. Suffer 2 strain to decrease difficulty of a Computers check to disable a security device or slice into a computer system by <${difficultyEmoji}>.`, item_restricted: `No` }),
        CurrencyShop.upsert({ name: '', search_name: '', cost: 0, item_encumberance: 0, item_rarity: 0, item_description: ``, item_restricted: `No` }),
        CurrencyShop.upsert({ name: '', search_name: '', cost: 0, item_encumberance: 0, item_rarity: 0, item_description: ``, item_restricted: `No` }),
        CurrencyShop.upsert({ name: '', search_name: '', cost: 0, item_encumberance: 0, item_rarity: 0, item_description: ``, item_restricted: `No` }),
        CurrencyShop.upsert({ name: '', search_name: '', cost: 0, item_encumberance: 0, item_rarity: 0, item_description: ``, item_restricted: `No` }),
        CurrencyShop.upsert({ name: '', search_name: '', cost: 0, item_encumberance: 0, item_rarity: 0, item_description: ``, item_restricted: `No` }),
        CurrencyShop.upsert({ name: '', search_name: '', cost: 0, item_encumberance: 0, item_rarity: 0, item_description: ``, item_restricted: `No` }),
        CurrencyShop.upsert({ name: '', search_name: '', cost: 0, item_encumberance: 0, item_rarity: 0, item_description: ``, item_restricted: `No` }),
 
 
       //CurrencyShop.upsert({ name: '', search_name: '', cost: 0, item_encumberance: 0, item_rarity: 0, item_description: ``, item_restricted: `No` }),
    ];

    await Promise.all(shop);
    console.log('Database synced');

    sequelize.close();
}).catch(console.error);